# Sets default memory used for gradle commands. Can be overridden by user or command line.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.debug=false

# Mod info
mod_id=villagecraft
mod_name=VillageCraft
mod_author=cmcintosh

# Minecraft version
minecraft_version=1.20.2
neoforge_version=20.2.88

# Dependency versions
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1