# Sets default memory used for gradle commands. Can be overridden by user or command line.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.debug=false

# NeoForge version
neo_version=47.1.3

# Mod info
mod_id=villagecraft
mod_name=VillageCraft
mod_author=cmcintosh
mod_group=com.villagecraft

# Minecraft version
minecraft_version=1.20.1

# Dependency versions
neogradle_version=7.0.80