modLoader="javafml" 
loaderVersion="[32,)" 
license="All rights reserved"
issueTrackerURL="http://github.com/cmcintosh/VillageCraft"
[[mods]] #mandatory
modId="vcm"
version="${file.jarVersion}" #mandatory
displayName="VillageCraft" #mandatory
displayURL="https://wembassy.com/" #optional
authors="Chris McIntosh<cmcintosh@wembassy.com>" #optional
description='''
VillageCraft is an attempt to bring much of the management functionality from games like
DwarfFortress into minecraft in order to make villages come more alive and become a larger
part of your play through.
'''
[[dependencies.villagecraft]]
    modId="forge" 
    mandatory=true 
    versionRange="[32,)" 
    ordering="NONE"
    side="BOTH"